### ISSUE TITLE
Add routine to find when two functions take equal time

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/tasty-bench-fit#3]
Take two `Word -> Benchmarkable` and return `Word` at which both of them take (roughly) the same time. 

We probably want to start narrowing down the range with rough `RelStDev` / `Timeout` and use finer ones only later on.

```haskell
data EqualizeConfig = EqualizeConfig {
  eqlBench1 :: Word -> Benchmarkable
  eqlBench2 :: Word -> Benchmarkable
  eqlLow :: Word
  eqlHigh :: Word
  eqlTimeout :: Timeout
  eqlRelStDev :: RelStDev
  }
```

**Comment by Bodigrim** [comment]
I'd imagine the following algorithm:
* Take a rough `RelStDev`, say 20%. Check that `eqlBench1` is significantly slower than `eqlBench2` at `eqlLow` (mean1 + stdev1 < mean2 - stdev2) and vice versa at `eqlHigh`.
* Take midpoint between `eqlLow` and `eqlHigh`, measure both functions. If measurements are significantly different, replace one of the endpoints with the midpoint and repeat. If measurements are not significantly different, decrease `RelStDev` and repeat. 
* Stop when `eqlLow + 1 = eqlHigh` or when `Timeout` happens before `RelStDev` is hit.

@wismill I noticed that you forked the repo. Is it a sign that you are interested to look into this issue? ;)

**Comment by wismill** [comment]
> @wismill I noticed that you forked the repo. Is it a sign that you are interested to look into this issue? ;)

Sorry, while I am very curious to see how this is implemented, I have other pending tasks. E.g. [`unicode-data`](https://github.com/composewell/unicode-data) and `cabal` deserves some love.
